# CICD to compile CV using Xelatex, store the PDF in output/, and send the PDF to S3

name: Build LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build p1
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./src
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Build p2
        uses: actions/upload-artifact@v3
        with:
          working-directory: ./src
          name: PDF
          path: main.pdf
      - name: Release p1
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'ref/tags/')
        with:
          working-directory: ./src
          files: main.PDF
            # - name: Release p2
            #uses: shallwefootball/s3-upload-action@master
            # with:
            #aws_key_id: ${{ secrets.AWS_KEY_ID }}
            #aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
