# CICD to compile CV using Xelatex, store the PDF in output/, and send the PDF to S3

name: Build LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }} 
      CI_COMMIT_MESSAGE: CICD GitHub Actions build
      CI_COMMIT_AUTHOR: Continuous Integration
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./src
          root_file: pmoehrke.tex

      - name: Move PDF to output/
        run: mv src/pmoehrke.pdf output/

      - name: Git commit static site artifacts
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "patrickm663@users.noreply.github.com"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

      - name: Push to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: "patrick-moehrke-cv-pdf"
          source_dir: output/
