# CICD to compile CV using Xelatex, store the PDF in output/, and send the PDF to S3

name: Build LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build p1
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Build p2
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      - name: Release
        uses: softproprs/action-gh-release@v1
        if: startersWith(github.ref, 'ref/tags/')
        with:
          files: main.PDF
