# CICD to compile CV using Xelatex, store the PDF in output/, and send the PDF to S3

name: Build LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git repo
        uses: actions/checkout@v3
      - name: Swtich to src/
        run: cd src/
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
